export const UNITS = [
  {
    id: 'unit_1',
    title: 'Starting Conversations',
    icon: 'chatbubbles-outline',
    color: '#3B82F6',
    lessons: [
      {
        id: 'l1_1',
        title: 'Why First Impressions Matter',
        duration: '3 min',
        summary: "Research shows you form a first impression in as little as 7 seconds - and it's very hard to change. The good news: warm, open body language and a genuine smile do most of the heavy lifting before you say a single word.",
        insight: 'Lead with warmth before words.',
        content: [
          {
            heading: 'The 7-Second Rule',
            body: "Researchers at Princeton found that people form judgments about trustworthiness and competence within milliseconds. By the time you've said your first sentence, a strong impression already exists - whether you meant to make one or not.",
            icon: 'timer-outline',
            color: '#3B82F6',
          },
          {
            heading: 'Body Over Words',
            body: "55% of a first impression comes from body language, 38% from tone of voice, and only 7% from actual words. Stand tall, make eye contact, and smile - these signal warmth and confidence before you open your mouth.",
            icon: 'body-outline',
            color: '#8B5CF6',
          },
          {
            heading: 'Lead With Warmth',
            body: "Warmth beats competence every time. People remember how you made them feel, not what you said. A genuine smile and open posture signal safety - and that's the foundation of every conversation that goes somewhere real.",
            icon: 'sunny-outline',
            color: '#F59E0B',
          },
        ],
        quiz: [
          {
            question: 'What percentage of a first impression comes from body language?',
            options: ['7%', '38%', '55%', '70%'],
            correct: 2,
          },
          {
            question: 'Which matters most in the first seconds of meeting someone?',
            options: ['The words you choose', 'Warmth and open body language', 'How impressive your background is', 'Your clothing'],
            correct: 1,
          },
          {
            question: 'People form first impressions in approximately...',
            options: ['30 seconds', '1 minute', '7 seconds', '5 minutes'],
            correct: 2,
          },
        ],
        practice: {
          scenarioId: 'networking',
          scenarioLabel: 'Networking Event',
          scenarioIcon: 'people-outline',
          scenarioColor: '#10B981',
          focus: 'Focus on your opening - speak with warmth and genuine enthusiasm. Let your words and tone signal that you are glad to meet them.',
        },
        trainerPrompt: "You are Jordan, meeting someone for the first time at a casual gathering. You were just introduced. React naturally to how warm and open they come across - if they greet you confidently and warmly, engage enthusiastically. If they seem flat or awkward, be politely reserved. Never mention social skills or techniques. Just be a real person. 1-2 sentences max per response.",
        challengeId: 'ch_04',
      },
      {
        id: 'l1_2',
        title: 'The FORD Technique',
        duration: '4 min',
        summary: 'FORD stands for Family, Occupation, Recreation, and Dreams. These four categories cover almost everything people love to talk about. When a conversation stalls, mentally pick one and ask an open-ended question.',
        insight: 'Ask about their world - not yours.',
        content: [
          {
            heading: 'What is FORD?',
            body: "FORD is a memory trick for keeping conversations alive. Family, Occupation, Recreation, Dreams - four universal topics that people almost always have strong feelings about. When a conversation slows, mentally pick one and ask.",
            icon: 'bookmark-outline',
            color: '#3B82F6',
          },
          {
            heading: 'How to Use It',
            body: "When silence hits, cycle through FORD mentally. Pick whichever feels natural and ask an open-ended question - 'What do you do in your free time?' or 'What made you get into that?' You don't need all four. One good one is enough.",
            icon: 'refresh-outline',
            color: '#F59E0B',
          },
          {
            heading: 'Follow Their Energy',
            body: "FORD is a starter, not a script. Watch for the moment they light up - speaking faster, leaning in, eyes engaging. That's the topic they actually want to talk about. When you see that signal, go deeper instead of moving on.",
            icon: 'flash-outline',
            color: '#10B981',
          },
        ],
        quiz: [
          {
            question: "What does the 'R' in FORD stand for?",
            options: ['Relationships', 'Recreation', 'Reality', 'Rapport'],
            correct: 1,
          },
          {
            question: "Someone mentions they love hiking. What's the best FORD follow-up?",
            options: ["That's cool, I've never hiked.", 'Oh nice. So what do you do for work?', "What's the most challenging trail you've done?", 'Do you like other sports too?'],
            correct: 2,
          },
          {
            question: 'FORD works best when you...',
            options: ['Cover all four topics in order', "Follow the person's energy and go deeper", 'Keep switching topics to stay interesting', 'Ask yes/no questions for quick answers'],
            correct: 1,
          },
        ],
        practice: {
          scenarioId: 'small_talk',
          scenarioLabel: 'Small Talk',
          scenarioIcon: 'chatbubble-outline',
          scenarioColor: '#F59E0B',
          focus: "Practice the FORD technique - when conversation slows, pick a topic and ask an open-ended question. Notice where Alex's energy picks up and follow it.",
        },
        trainerPrompt: "You are Casey, making small talk with someone you just met. You have a job you like (marketing), a hobby you love (cooking), a close family, and a dream of opening a small restaurant someday. Respond naturally and briefly to whatever they ask. When they hit a topic you care about, show a bit more energy. Never mention conversation techniques. 1-2 sentences max per response.",
        challengeId: 'ch_06',
      },
      {
        id: 'l1_3',
        title: 'Breaking the Ice in Groups',
        duration: '5 min',
        summary: 'Joining a group mid-conversation feels awkward, but most groups welcome it. Make eye contact with the friendliest-looking person, wait for a natural pause, and offer a relevant comment - not a question.',
        insight: 'A comment gets you in. A question puts you on the spot.',
        content: [
          {
            heading: "Why Groups Feel Hard",
            body: "Joining a mid-conversation group triggers social anxiety because we fear disrupting or being rejected. But most groups are actually open to new people - the barrier is almost entirely in your head.",
            icon: 'people-outline',
            color: '#3B82F6',
          },
          {
            heading: 'Comment, Don\'t Question',
            body: "Don't open with a question - it puts pressure on everyone to respond. Instead, make a relevant comment or observation about what they're discussing. A comment invites a response without demanding one.",
            icon: 'chatbubble-outline',
            color: '#8B5CF6',
          },
          {
            heading: 'Timing and Entry',
            body: "Wait for a natural pause, make brief eye contact with the friendliest person, and step slightly into the circle. Your body language signals 'I'm joining' before you say a word - and that's completely okay.",
            icon: 'enter-outline',
            color: '#10B981',
          },
        ],
        quiz: [
          {
            question: 'When joining a group conversation, you should open with...',
            options: ['A direct question to get involved', 'A comment about what they\'re discussing', 'An introduction and your background', 'Interrupting at the first gap'],
            correct: 1,
          },
          {
            question: "Why do comments work better than questions when joining groups?",
            options: ['Questions sound interrogative and demand responses', 'Comments are always shorter', 'Questions are too personal', 'Comments are more interesting'],
            correct: 0,
          },
          {
            question: 'Before stepping in, make eye contact with...',
            options: ['The person talking the most', 'The most senior person', 'The friendliest-looking person', 'Everyone at once'],
            correct: 2,
          },
        ],
        practice: {
          scenarioId: 'networking',
          scenarioLabel: 'Networking Event',
          scenarioIcon: 'people-outline',
          scenarioColor: '#10B981',
          focus: "Imagine Dana is already in a conversation. Practice inserting yourself with a comment, not a question. Stay for at least 3 exchanges before the conversation moves naturally.",
        },
        trainerPrompt: "You are Dana, mid-conversation with a friend at a social event when someone new approaches. If they ease in with a relevant comment or observation, welcome them naturally into the conversation. If they interrupt with an unrelated question, react with mild surprise but still be polite. Never mention social skills. Just react like a real person would. 1-2 sentences max per response.",
        challengeId: 'ch_11',
      },
      {
        id: 'l1_4',
        title: 'Ending Conversations Gracefully',
        duration: '4 min',
        summary: "Dragging out a goodbye or cutting it off abruptly both feel bad. The trick: signal the end before you start it. 'I'll let you get back to it' gives the other person a moment to mentally close the loop.",
        insight: 'Signal before you close.',
        content: [
          {
            heading: "Why Endings Feel Awkward",
            body: "Most conversation endings are awkward because they're either too abrupt or drag out painfully. One person cuts off suddenly; or both people know it's over but keep talking out of politeness. Neither feels good.",
            icon: 'alert-circle-outline',
            color: '#EF4444',
          },
          {
            heading: 'Signal Before You Close',
            body: "Good endings start with a signal phrase: 'I should let you get back to it' or 'Before I head off...' This gives the other person a moment to mentally prepare. Then close warmly and naturally.",
            icon: 'flag-outline',
            color: '#F59E0B',
          },
          {
            heading: 'Leave on a High Note',
            body: "End while the conversation still has energy. Reference something specific they said: 'It was great hearing about your trip - I hope it goes well.' Specific endings feel genuine. Generic ones feel like a chore.",
            icon: 'star-outline',
            color: '#3B82F6',
          },
        ],
        quiz: [
          {
            question: "What's the best way to start ending a conversation?",
            options: ["Stop talking and walk away", "Say 'I have to go now'", "Use a signal phrase first", "Wait for them to end it"],
            correct: 2,
          },
          {
            question: 'The ideal time to end a conversation is...',
            options: ['When you run out of things to say', 'While the energy is still good', 'After an awkward pause naturally forms', 'When the other person goes quiet'],
            correct: 1,
          },
          {
            question: "Which closing sounds most genuine?",
            options: ["'Nice talking to you!'", "'See you around.'", "'It was great hearing about your project - good luck with it.'", "'Anyway, I should go.'"],
            correct: 2,
          },
        ],
        practice: {
          scenarioId: 'small_talk',
          scenarioLabel: 'Small Talk',
          scenarioIcon: 'chatbubble-outline',
          scenarioColor: '#F59E0B',
          focus: "Practice ending the conversation gracefully - use a signal phrase when you feel ready to close. Aim to leave while the energy is still positive.",
        },
        trainerPrompt: "You are Alex, having a pleasant chat with someone you just met at a social gathering. Chat naturally - ask them something, share something brief about yourself. When they signal they want to wrap up, react to how they do it: if they use a warm close and reference something you discussed, feel good about it. If they abruptly stop or give a generic goodbye, react with a slightly flat 'Oh, okay.' Never mention conversation techniques. 1-2 sentences max per response.",
        challengeId: 'ch_05',
      },
    ],
  },
  {
    id: 'unit_2',
    title: 'Active Listening',
    icon: 'ear-outline',
    color: '#10B981',
    lessons: [
      {
        id: 'l2_1',
        title: 'The Listening Trap',
        duration: '3 min',
        summary: "Most people 'listen' while waiting for their turn to speak. Real listening means suspending your internal monologue and focusing entirely on what the other person is saying - including what they're not saying.",
        insight: 'Listen to understand, not to respond.',
        content: [
          {
            heading: "Are You Actually Listening?",
            body: "Studies show people listen at only 25% efficiency - 75% of what someone says is lost. Most of that gap is because our brains process faster than speech, so we fill the space with our own thoughts.",
            icon: 'ear-outline',
            color: '#10B981',
          },
          {
            heading: 'The Reply Trap',
            body: "The most common form of fake listening: mentally preparing your response while someone is still talking. You catch enough words to respond - but you miss the meaning, the emotion, and the full picture.",
            icon: 'sync-outline',
            color: '#EF4444',
          },
          {
            heading: 'What Real Listening Looks Like',
            body: "Real listening means suspending your internal monologue. Let silence be okay. Let them finish completely. Notice their tone, their pace, what they're choosing not to say. Your response will be better for it.",
            icon: 'checkmark-circle-outline',
            color: '#10B981',
          },
        ],
        quiz: [
          {
            question: 'Why do people often retain only 25% of what they hear?',
            options: ["They're not interested", "The brain processes faster than speech and fills the gap", "The speaker talks too fast", "They're distracted by their phone"],
            correct: 1,
          },
          {
            question: "The 'reply trap' is when you...",
            options: ['Talk too much', 'Prepare your response while they\'re still talking', 'Ask too many questions', 'Stay completely quiet'],
            correct: 1,
          },
          {
            question: 'Real listening requires...',
            options: ['Nodding frequently to signal attention', 'Suspending your internal monologue', 'Taking mental notes of key points', 'Maintaining constant eye contact'],
            correct: 1,
          },
        ],
        practice: {
          scenarioId: 'new_friends',
          scenarioLabel: 'Making Friends',
          scenarioIcon: 'person-add-outline',
          scenarioColor: '#3B82F6',
          focus: "Focus entirely on what Sam says - not on what you'll say next. Let responses come naturally after they finish. Notice how much you actually catch when you stop pre-planning.",
        },
        trainerPrompt: "You are Sam, sharing a story about a mildly frustrating week - you had a project at work that didn't get recognized, and you're feeling a bit underappreciated. Share naturally in pieces. If the person responds to what you actually said with a relevant question or comment, open up a bit more. If they talk about themselves or respond vaguely, pull back slightly. Never mention listening skills. Just be a real person. 1-2 sentences max per response.",
        challengeId: 'ch_17',
      },
      {
        id: 'l2_2',
        title: "Ask, Don't Assume",
        duration: '4 min',
        summary: "Curiosity-driven questions - 'What was that like for you?' - show genuine engagement. Avoid yes/no questions. The best follow-up is always a more specific version of something the person just shared.",
        insight: 'Your follow-up question is your grade.',
        content: [
          {
            heading: 'Curiosity as a Skill',
            body: "Most people ask surface questions and move on. The person who stands out is the one who goes deeper - not intrusively, but with genuine curiosity about the specific thing the other person just shared.",
            icon: 'search-outline',
            color: '#10B981',
          },
          {
            heading: 'Open vs. Closed Questions',
            body: "Closed questions end conversations: 'Did you like it?' - 'Yeah.' Open questions open them: 'What was that like for you?' gives the person room to share something real. One word can be the difference.",
            icon: 'git-branch-outline',
            color: '#3B82F6',
          },
          {
            heading: 'The Best Follow-Up Formula',
            body: "The best follow-up is always a more specific version of what they just said. If they mention they love travelling, don't ask 'Where have you been?' Ask 'What's a trip that actually changed how you see something?'",
            icon: 'arrow-forward-outline',
            color: '#8B5CF6',
          },
        ],
        quiz: [
          {
            question: "Which is the better follow-up when someone mentions they love travelling?",
            options: ["'Did you enjoy the last trip?'", "'Where do you like to go?'", "'What's a trip that changed how you see something?'", "'How long are you usually gone?'"],
            correct: 2,
          },
          {
            question: 'Open questions work better because they...',
            options: ['Are shorter and easier to answer', 'Give the person room to share something real', 'Avoid awkward topics', 'Keep conversations moving quickly'],
            correct: 1,
          },
          {
            question: 'The best follow-up question is...',
            options: ['A change of topic', 'A more specific version of what they just said', 'Something about yourself', 'A yes or no question for clarity'],
            correct: 1,
          },
        ],
        practice: {
          scenarioId: 'new_friends',
          scenarioLabel: 'Making Friends',
          scenarioIcon: 'person-add-outline',
          scenarioColor: '#3B82F6',
          focus: "Only ask open-ended questions. For every topic Sam raises, dig one level deeper with a specific follow-up before moving on. Avoid yes/no questions entirely.",
        },
        trainerPrompt: "You are Riley, someone who just got back from two weeks in Portugal and also loves rock climbing on weekends. You open up and share more when someone asks specific, curious questions - 'What was the most unexpected thing about the trip?' gets you talking. A generic 'Did you have fun?' gets a short 'Yeah, it was great.' Never mention question types or conversation skills. Just respond naturally. 1-2 sentences max per response.",
        challengeId: 'ch_08',
      },
      {
        id: 'l2_3',
        title: 'Reflecting & Paraphrasing',
        duration: '5 min',
        summary: "After someone shares something meaningful, reflect it back: 'So it sounds like you felt overlooked?' This confirms understanding and makes them feel truly heard - which is rarer than most people think.",
        insight: 'Feeling heard is the foundation of every real connection.',
        content: [
          {
            heading: 'What is Reflecting?',
            body: "Reflecting means feeding back the emotional content of what someone said, in your own words: 'So it sounds like you felt left out?' It confirms understanding and signals that you actually processed what they shared.",
            icon: 'repeat-outline',
            color: '#10B981',
          },
          {
            heading: 'Paraphrasing in Practice',
            body: "Paraphrasing is summarizing the facts: 'So if I'm hearing you right, you've been working on this for months but haven't gotten credit yet?' This shows you processed the full picture - not just the surface.",
            icon: 'document-text-outline',
            color: '#3B82F6',
          },
          {
            heading: 'Why It Works',
            body: "Feeling heard is rare. Most people spend conversations managing their own anxiety about what to say next. When you reflect accurately, the other person feels understood - which creates real connection almost instantly.",
            icon: 'heart-outline',
            color: '#F59E0B',
          },
        ],
        quiz: [
          {
            question: "Reflecting someone's emotions back to them shows...",
            options: ['You have a good memory', 'You were processing your response', 'You heard and understood them', 'You agree with their feelings'],
            correct: 2,
          },
          {
            question: "'So it sounds like you felt overlooked?' is an example of...",
            options: ['Paraphrasing the facts', 'Reflecting the emotion', 'Asking a closed question', 'Making an assumption'],
            correct: 1,
          },
          {
            question: 'Why is feeling heard so powerful?',
            options: ["It makes people automatically like you more", "It's genuinely rare - most people are planning their response", "It proves you're skilled at conversation", "It keeps conversations going longer"],
            correct: 1,
          },
        ],
        practice: {
          scenarioId: 'new_friends',
          scenarioLabel: 'Making Friends',
          scenarioIcon: 'person-add-outline',
          scenarioColor: '#3B82F6',
          focus: "When Sam shares something personal, practice reflecting the emotion back before responding. Use phrases like 'So it sounds like...' or 'If I'm hearing you right...' at least twice.",
        },
        trainerPrompt: "You are Taylor, opening up about feeling burnt out at your job. You're not sure you're on the right path and it's been weighing on you. Share in pieces. If the other person reflects your feelings back - 'So it sounds like you feel...', 'If I'm hearing you right...' - feel genuinely understood and share more. If they jump straight to advice or change the subject, feel a bit dismissed and pull back. Never mention listening or reflection techniques. Just be a real person. 1-2 sentences max per response.",
        challengeId: 'ch_19',
      },
      {
        id: 'l2_4',
        title: 'Staying Present',
        duration: '3 min',
        summary: "Your phone, background noise, what you're having for dinner - all compete for your attention. One trick: mentally narrate what the other person is saying as they say it. It forces your brain to process their words.",
        insight: 'Presence is a choice you make every few seconds.',
        content: [
          {
            heading: 'The Attention War',
            body: "Your phone, your to-do list, background noise, what you're having for dinner - all of it competes with the person in front of you. Attention is finite, and most of it is already spoken for before the conversation even starts.",
            icon: 'wifi-outline',
            color: '#10B981',
          },
          {
            heading: 'The Narration Trick',
            body: "One of the most effective techniques for staying present: mentally narrate what the other person is saying as they say it. It forces your brain to actively process their words instead of drifting to your own thoughts.",
            icon: 'mic-outline',
            color: '#3B82F6',
          },
          {
            heading: 'Presence is a Practice',
            body: "You can't force presence for an entire conversation - your mind will wander. The skill is noticing when it wanders and gently returning. Every time you catch yourself and refocus, you're training your listening like a muscle.",
            icon: 'fitness-outline',
            color: '#8B5CF6',
          },
        ],
        quiz: [
          {
            question: 'The narration trick works because...',
            options: ["It helps you remember what they said", "It forces your brain to actively process their words", "It keeps you from saying the wrong thing", "It naturally slows the conversation"],
            correct: 1,
          },
          {
            question: "The realistic goal for staying present in a conversation is...",
            options: ['Never letting your mind wander', 'Noticing when it wanders and returning', 'Staying fully focused the entire time', 'Avoiding all external distractions'],
            correct: 1,
          },
          {
            question: 'Presence is best described as...',
            options: ['A natural talent you either have or not', 'A permanent state you can achieve', 'A practice you build over time', 'A state of total concentration'],
            correct: 2,
          },
        ],
        practice: {
          scenarioId: 'small_talk',
          scenarioLabel: 'Small Talk',
          scenarioIcon: 'chatbubble-outline',
          scenarioColor: '#F59E0B',
          focus: "Use the narration trick throughout - mentally repeat what Alex says as they say it. Notice when your mind drifts to your response and redirect it back to their words.",
        },
        trainerPrompt: "You are Quinn, excitedly sharing that you just started learning guitar and are planning a road trip next month. You drop specific details - the route you're taking, the songs you're learning. If the other person picks up on a specific detail and responds to it, react with enthusiasm. If they respond vaguely or off-topic, gently notice: 'Oh - yeah, anyway...' and continue. Never mention presence or attention. Just be a real person. 1-2 sentences max per response.",
        challengeId: 'ch_17',
      },
    ],
  },
  {
    id: 'unit_3',
    title: 'Reading Body Language',
    icon: 'body-outline',
    color: '#8B5CF6',
    locked: true,
    lessons: [
      { id: 'l3_1', title: 'What Your Posture Says',  duration: '4 min', summary: '', insight: '' },
      { id: 'l3_2', title: 'Eye Contact Signals',      duration: '3 min', summary: '', insight: '' },
      { id: 'l3_3', title: 'Mirroring Others',         duration: '5 min', summary: '', insight: '' },
      { id: 'l3_4', title: 'Spotting Discomfort',      duration: '4 min', summary: '', insight: '' },
    ],
  },
  {
    id: 'unit_4',
    title: 'Handling Awkward Moments',
    icon: 'alert-circle-outline',
    color: '#F59E0B',
    locked: true,
    lessons: [
      { id: 'l4_1', title: "Silence Isn't Weird",          duration: '3 min', summary: '', insight: '' },
      { id: 'l4_2', title: 'When You Say the Wrong Thing',   duration: '4 min', summary: '', insight: '' },
      { id: 'l4_3', title: 'Recovering a Conversation',      duration: '5 min', summary: '', insight: '' },
    ],
  },
  {
    id: 'unit_5',
    title: 'Group Dynamics',
    icon: 'people-outline',
    color: '#F43F5E',
    locked: true,
    lessons: [
      { id: 'l5_1', title: 'Finding Your Role',                    duration: '4 min', summary: '', insight: '' },
      { id: 'l5_2', title: 'Managing Dominant Personalities',       duration: '5 min', summary: '', insight: '' },
      { id: 'l5_3', title: 'Contributing Without Interrupting',     duration: '4 min', summary: '', insight: '' },
    ],
  },
];
